language: python

python:
    - 2.7

env:
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==16.1.1 PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==16.1.0 PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==16.0.0 PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==15.5.0 PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==15.4.0 PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==15.3.0 PYOPENSSL=PyOpenSSL
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk PYOPENSSL=
  - TWISTED=Twisted==16.1.1 PYOPENSSL=
  - TWISTED=Twisted==16.1.0 PYOPENSSL=
  - TWISTED=Twisted==16.0.0 PYOPENSSL=
  - TWISTED=Twisted==15.5.0 PYOPENSSL=
  - TWISTED=Twisted==15.4.0 PYOPENSSL=
  - TWISTED=Twisted==15.3.0 PYOPENSSL=

install:
  - pip install $TWISTED --use-mirrors
  - 'test -n "$PYOPENSSL" && pip install $PYOPENSSL --use-mirrors || true'
  - python setup.py install

script:
  - cd tests;trial xep124;trial testparser;trial xep206
